name: Build WebGoat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: dbreitel/my-webgoat
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -B -DskipTests   

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgoat-jar
          path: webgoat-server/target/webgoat*.jar  # This assumes the JAR is in the 'target' directory
