name: Build WebGoat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the WebGoat repository
      - name: Checkout WebGoat
        uses: actions/checkout@v3
        with:
          repository: WebGoat/WebGoat
          ref: main  # Specify a branch, tag, or commit

      # Step 2: Set up a newer JDK (e.g., Java 17 or 20)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Replace with '20' if you want Java 20
          distribution: 'temurin'  # 'adopt' can also be used
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package -B -DskipTests

      # Step 4: Upload the built JAR file as an artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webgoat-jar
          path: target/*.jar  # Adjust path if JAR is stored elsewhere
